.TH "FWD DEFAULT" "1" "2026-08-12" "fwdit" "fwd default Manual"
.SH NAME
fwd\-default \- Set the command bare 'fwd' launches; shorthand for 'fwd
config set default_command ...'.
.SH SYNOPSIS
.B fwd default
[OPTIONS] [command]...
.SH DESCRIPTION
Set the command bare 'fwd' launches; shorthand for 'fwd config set
default_command ...'.
.PP
Use '--' before command flags, for example: fwd default --project --
python -m my_agent
.SH OPTIONS
.TP
\fB\-\-user\fP
Set the user-wide default in ~/.fwd/config.toml; this is the default scope.
.TP
\fB\-\-project\fP
Set the default only for the current project.
.TP
\fB\-t,\fP \-\-target <str>
Set the default for one target; target settings override project and
user settings.
.SH EXIT STATUS
\fB0\fP indicates success. Any nonzero value indicates an error.
.SH REPORTING BUGS
Report issues at \fIhttps://github.com/Sid-MB/fwd/issues\fP.
.SH SEE ALSO
\fBfwd\fP(1)
