#!/usr/bin/env bash
# Establish fwd's persistent remote environment and tmux prerequisite.
#
# Language runtimes, package managers, and coding agents deliberately do not live here. Class-based toolchains and
# Agent classes return shared ToolRequirement objects to the Python resolver, which probes the remote PATH first and runs
# only the missing tools' user-space fallback installers. Keeping this script tool-agnostic prevents a Swift, Haskell,
# shell, or arbitrary-command launch from downloading unrelated Python, JavaScript, Claude, or Codex tooling.

set -euo pipefail

FWD_BOOTSTRAP_VERSION=5

: "${FWD_TOOL_PREFIX:?bootstrap requires FWD_TOOL_PREFIX}"
: "${FWD_REMOTE_DIR:?bootstrap requires FWD_REMOTE_DIR}"
FWD_COMMAND_NAME="${FWD_COMMAND_NAME:-command}"
FWD_SCRATCH="${FWD_SCRATCH:-$FWD_TOOL_PREFIX/scratch}"
FWD_BOOTSTRAP_MINIMAL="${FWD_BOOTSTRAP_MINIMAL:-0}"

BIN_DIR="$FWD_TOOL_PREFIX/bin"
BUN_ROOT="$FWD_TOOL_PREFIX/bun"
NPM_ROOT="$FWD_TOOL_PREFIX/npm"
CLAUDE_ROOT="$FWD_TOOL_PREFIX/claude"
ENV_FILE="$FWD_TOOL_PREFIX/fwd-env.sh"
HOME_ENV_FILE="$HOME/.fwd-env.sh"
MARKER="$FWD_TOOL_PREFIX/.fwd-bootstrap-$FWD_BOOTSTRAP_VERSION"

log() { printf '%s: %s\n' "$FWD_COMMAND_NAME" "$*"; }
fail() { printf '%s: error: %s\n' "$FWD_COMMAND_NAME" "$*" >&2; exit 1; }
have() { command -v "$1" >/dev/null 2>&1; }

mkdir -p "$BIN_DIR" "$FWD_SCRATCH" "$FWD_REMOTE_DIR"
export PATH="$BIN_DIR:$BUN_ROOT/bin:$NPM_ROOT/bin:$CLAUDE_ROOT/bin:$HOME/.local/bin:$PATH"

bootstrap_is_valid() {
    [ -f "$MARKER" ] || return 1
    [ -f "$HOME_ENV_FILE" ] || return 1
    if [ "$FWD_BOOTSTRAP_MINIMAL" = "1" ]; then return 0; fi
    have tmux && tmux -V >/dev/null 2>&1
}

if bootstrap_is_valid; then
    log "bootstrap $FWD_BOOTSTRAP_VERSION already applied at $FWD_TOOL_PREFIX (marker present), skipping"
    exit 0
fi
rm -f "$FWD_TOOL_PREFIX"/.fwd-bootstrap-* 2>/dev/null || true

write_env_file() {
    cat >"$ENV_FILE" <<EOF
# Generated by $FWD_COMMAND_NAME bootstrap v$FWD_BOOTSTRAP_VERSION. Do not edit; it is rewritten on every version bump.
export FWD_TOOL_PREFIX="$FWD_TOOL_PREFIX"
export FWD_REMOTE_DIR="$FWD_REMOTE_DIR"
export FWD_SCRATCH="$FWD_SCRATCH"

case ":\$PATH:" in
    *":$BIN_DIR:"*) ;;
    *) export PATH="$BIN_DIR:$BUN_ROOT/bin:$NPM_ROOT/bin:$CLAUDE_ROOT/bin:\$HOME/.local/bin:\$PATH" ;;
esac

export UV_CACHE_DIR="$FWD_SCRATCH/uv-cache"
export UV_PYTHON_INSTALL_DIR="$FWD_TOOL_PREFIX/uv-python"
export BUN_INSTALL="$BUN_ROOT"
export BUN_INSTALL_CACHE_DIR="$FWD_SCRATCH/bun-cache"
export npm_config_cache="$FWD_SCRATCH/npm-cache"
export npm_config_prefix="$NPM_ROOT"
export XDG_CACHE_HOME="\${XDG_CACHE_HOME:-$FWD_SCRATCH/cache}"
EOF
    log "wrote $ENV_FILE"

    cat >"$HOME_ENV_FILE" <<EOF
# Generated by $FWD_COMMAND_NAME bootstrap v$FWD_BOOTSTRAP_VERSION. This fixed pointer lets non-login SSH commands find the backend-specific persistent environment.
[ -f "$ENV_FILE" ] && . "$ENV_FILE"
EOF
    log "wrote $HOME_ENV_FILE"
}

install_shell_hook() {
    local marker_comment="# fwd environment"
    local line="[ -f \"$ENV_FILE\" ] && . \"$ENV_FILE\""
    local rc
    for rc in "$HOME/.bashrc" "$HOME/.profile"; do
        touch "$rc" 2>/dev/null || continue
        if grep -qF "$ENV_FILE" "$rc" 2>/dev/null; then continue; fi
        printf '\n%s\n%s\n' "$marker_comment" "$line" >>"$rc"
        log "added fwd-env hook to $rc"
    done
}

install_tmux() {
    if have tmux; then
        log "tmux present: $(tmux -V 2>/dev/null || echo unknown)"
        return 0
    fi
    if [ "$(id -u)" = "0" ] && have apt-get; then
        log "installing tmux via apt-get"
        DEBIAN_FRONTEND=noninteractive apt-get update -qq >/dev/null 2>&1 || true
        DEBIAN_FRONTEND=noninteractive apt-get install -y -qq tmux >/dev/null 2>&1 || true
    fi
    have tmux || fail "tmux is required but not installed, and $FWD_COMMAND_NAME cannot install it (no root / no apt-get). Install tmux on the remote host and retry."
}

log "bootstrap v$FWD_BOOTSTRAP_VERSION prefix=$FWD_TOOL_PREFIX remote_dir=$FWD_REMOTE_DIR scratch=$FWD_SCRATCH"
write_env_file
install_shell_hook
if [ "$FWD_BOOTSTRAP_MINIMAL" = "1" ]; then
    log "FWD_BOOTSTRAP_MINIMAL=1: skipping tmux installation"
else
    install_tmux
fi
date -u +"%Y-%m-%dT%H:%M:%SZ" >"$MARKER" 2>/dev/null || : >"$MARKER"
log "bootstrap complete"
