"""Remote tmux-backed execution for durable send tasks.

One hidden manager session is created per fwd session and retained by a tiny idle control window. Each command or
agent turn gets its own named window, process group, append-only output log, and exit marker under
``~/.fwd/tasks/<session>/<task>``. The user follows logs through an ordinary non-interactive SSH connection, so
backgrounding the viewer cannot send a hangup to the actual work.
"""

from __future__ import annotations

import re
import shlex
import subprocess

from fwd import remote
from fwd.send_tasks import SendTask
from fwd.sshexec import SSHEndpoint


def _safe(value: str) -> str:
    """Constrain remote tmux/path identifiers to the alphabet generated by fwd."""
    return re.sub(r"[^A-Za-z0-9_-]+", "-", value).strip("-") or "task"


def manager_name(session_name: str) -> str:
    """Return the hidden tmux session that owns send-task windows."""
    return f"fwd-tasks-{_safe(session_name)}"


def task_dir(session_name: str, task_id: str) -> str:
    """Return a shell expression for this task's remote metadata directory."""
    return f'$HOME/.fwd/tasks/{_safe(session_name)}/{_safe(task_id)}'


def _target(session_name: str, task_id: str | None = None) -> str:
    value = manager_name(session_name)
    if task_id:
        value += f":{_safe(task_id)}"
    return remote._tmux_exact_target(value)


def ensure_manager(endpoint: SSHEndpoint, session_name: str) -> None:
    """Create the task manager's idle control window if it does not already exist."""
    manager = manager_name(session_name)
    keepalive = "while :; do sleep 86400; done"
    create = shlex.join(["tmux", "new-session", "-d", "-s", manager, "-n", "_fwd", "bash", "-lc", keepalive])
    endpoint.run(f"{remote._source_env()}tmux has-session -t {_target(session_name)} 2>/dev/null || {create}", check=True)


def start(endpoint: SSHEndpoint, session_name: str, remote_dir: str, task: SendTask) -> None:
    """Start ``task.command`` in a new durable window and initialize its log files."""
    ensure_manager(endpoint, session_name)
    directory = task_dir(session_name, task.id)
    dependency = task_dir(session_name, task.depends_on) if task.depends_on else None
    initial_state = "queued" if dependency else "running"
    wait = f'while [ ! -f "{dependency}/exit" ]; do sleep 0.2; done; printf "running\\n" > "$task_dir/state"; ' if dependency else ""
    command = shlex.join(task.command)
    body = (
        f'task_dir="{directory}"; mkdir -p "$task_dir"; : > "$task_dir/output"; rm -f "$task_dir/exit"; printf "{initial_state}\\n" > "$task_dir/state"; '
        f"{wait}"
        f"{remote._source_env()}cd {shlex.quote(remote_dir)} && {command}; "
        f'rc=$?; printf "%s\\n" "$rc" > "$task_dir/exit"; printf "done\\n" > "$task_dir/state"; exit "$rc"'
    )
    window = shlex.join(
        [
            "tmux",
            "new-window",
            "-d",
            "-t",
            manager_name(session_name),
            "-n",
            _safe(task.id),
            "-c",
            remote_dir,
            "bash",
            "-lc",
            f"{body} >> \"{directory}/output\" 2>&1",
        ]
    )
    endpoint.run(f'task_dir="{directory}"; mkdir -p "$task_dir"; {window}', check=True)


def status(endpoint: SSHEndpoint, task: SendTask) -> tuple[str, int | None]:
    """Return live status and exit code from the remote marker/window."""
    directory = task_dir(task.session, task.id)
    command = (
        f'if [ -f "{directory}/exit" ]; then printf "done "; cat "{directory}/exit"; '
        f'elif [ -f "{directory}/state" ] && [ "$(cat "{directory}/state")" = queued ]; then printf queued; '
        f"elif tmux list-windows -t {_target(task.session)} -F '#{{window_name}}' 2>/dev/null | grep -Fxq {shlex.quote(_safe(task.id))}; then printf running; "
        "else printf unknown; fi"
    )
    result = endpoint.run(command, check=False)
    text = result.stdout.strip()
    if text.startswith("done "):
        try:
            code = int(text.split(maxsplit=1)[1])
        except (IndexError, ValueError):
            code = 1
        return ("completed" if code == 0 else "failed", code)
    return (text if text in {"queued", "running", "unknown"} else "unknown", None)


def stop(endpoint: SSHEndpoint, task: SendTask) -> None:
    """Cancel a task window and leave a conventional signal-style exit code for future viewers."""
    directory = task_dir(task.session, task.id)
    command = (
        f"tmux kill-window -t {_target(task.session, task.id)} 2>/dev/null || true; "
        f'mkdir -p "{directory}"; if [ ! -f "{directory}/exit" ]; then printf "130\\n" > "{directory}/exit"; fi'
    )
    endpoint.run(command, check=False)


def kill_manager(endpoint: SSHEndpoint, session_name: str) -> None:
    """Kill every send-task window for one fwd session; no-op when none exist."""
    command = f"tmux kill-session -t {_target(session_name)} 2>/dev/null || true"
    endpoint.run(command, check=False)


def follow_process(endpoint: SSHEndpoint, task: SendTask) -> subprocess.Popen[bytes]:
    """Start an SSH log follower that exits with the remote task's final status."""
    directory = task_dir(task.session, task.id)
    window_alive = f"tmux list-windows -t {_target(task.session)} -F '#{{window_name}}' 2>/dev/null | grep -Fxq {shlex.quote(_safe(task.id))}"
    follow = (
        f'task_dir="{directory}"; '
        f'while [ ! -f "$task_dir/output" ]; do if [ -f "$task_dir/exit" ]; then break; fi; if ! {window_alive}; then mkdir -p "$task_dir"; : > "$task_dir/output"; printf "1\\n" > "$task_dir/exit"; break; fi; sleep 0.1; done; '
        'touch "$task_dir/output"; tail -n +1 -F "$task_dir/output" & follower=$!; '
        "trap 'kill \"$follower\" 2>/dev/null || true' EXIT HUP TERM; "
        f'while [ ! -f "$task_dir/exit" ]; do if ! {window_alive}; then printf "1\\n" > "$task_dir/exit"; break; fi; sleep 0.2; done; sleep 0.2; '
        'kill "$follower" 2>/dev/null || true; wait "$follower" 2>/dev/null || true; '
        'exit "$(cat "$task_dir/exit" 2>/dev/null || printf 1)"'
    )
    return endpoint.popen(follow, stdin=subprocess.DEVNULL, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
